/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fulladder(A, B, C, sum, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input A;
  input B;
  input C;
  output co;
  output sum;
  wire w1;
  wire w2;
  wire w3;
  sky130_fd_sc_hd__maj3_1 _10_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xor3_1 _11_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_03_)
  );
  assign w1 = _07_;
  assign sum = _08_;
  assign co = _09_;
  assign w2 = _05_;
  assign w3 = _06_;
  assign _02_ = C;
  assign _00_ = A;
  assign _01_ = B;
  assign _09_ = _04_;
  assign _08_ = _03_;
endmodule
